### ISSUE TITLE
我在黑马的视频看过这一份项目了。

### ISSUE THREAD

**Issue by xieguanliang** [muyinchen/migoshop2.0#1]
不知道你是不是那位老师。。。。

**Comment by muyinchen** [comment]
我就是在此基础上进行迭代深入的，对原有老技术继续升级和改造，并加入全新的东西，比如最新的那个sso系统，可参照，后面还会用reactive进行改造，相关的资料你可以搜下谷歌或者百度的，一些东西看自己的时间了，最近忙着分布式数据平台的东西，所以也一直没更新博客，也就放出了一个sso，第三版的很多东西虽然开发出来了，但还在斟酌用哪些来呈现更好，更能让大伙学到东西

**Comment by xieguanliang** [comment]
不错，不错，挺好的。😁

**Comment by wushijing30** [comment]
求黑马的这个视频！ @xieguanliang 
:grin:

**Comment by Jims-ml** [comment]
同求！ @xieguanliang
😁

**Comment by muyinchen** [comment]
不好意思，没有视频哦，不过此项目内的一些东西已在后面版本中迭代完毕，全新的技术实现，和原版有很大区别，碍于博客没时间写，近期也确实忙，再构思好了会一并放出的，敬请期待
